// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADdST9MimAPEeHuYVgJXLlij5mJ8Z8NXY',
    appId: '1:137939624185:web:16eafea4aa2d0a155fc228',
    messagingSenderId: '137939624185',
    projectId: 'aerovania-app-1',
    authDomain: 'aerovania-app-1.firebaseapp.com',
    storageBucket: 'aerovania-app-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMHStlAqMaDulMuu7lelPokMviSGrOJM',
    appId: '1:137939624185:android:9cd831db7c06339d5fc228',
    messagingSenderId: '137939624185',
    projectId: 'aerovania-app-1',
    storageBucket: 'aerovania-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpig3mzbP3cSFHpitZG_EtBbXcIPtQ7y0',
    appId: '1:137939624185:ios:4a4cced6a0e535e05fc228',
    messagingSenderId: '137939624185',
    projectId: 'aerovania-app-1',
    storageBucket: 'aerovania-app-1.appspot.com',
    iosBundleId: 'com.example.aerovaniaApp1',
  );

}